// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;
import ballerina/io;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
final Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");


final string testFeedbackSubmissionId = "392813793683";

@test:Config {}
isolated function getPageOfFeedbackSubmissions() returns error? {
    CollectionResponseSimplePublicObjectWithAssociationsForwardPaging response = check baseClient->/crm/v3/objects/feedback_submissions;
    test:assertTrue(response?.results.length()>=0); 
    io:println("Retrieved feedback submissions: " ,response?.results.length());                                             
}

@test:Config {}
isolated function  getFeedbackSubmissionById() returns error? { 
    SimplePublicObjectWithAssociations response = check baseClient->/crm/v3/objects/feedback_submissions/[testFeedbackSubmissionId];
    test:assertTrue(response?.properties == 
            {   
                "hs_createdate": "2024-12-22T07:28:21.099Z",
                "hs_lastmodifieddate": "2024-12-22T07:28:21.328Z",
                "hs_object_id": "392813793683"
            }   
        );
    io:println("Requested feedback submission: " ,response?.properties);
}

@test:Config {}
isolated function  searchFeedbackSubmissions() returns error?{
    CollectionResponseWithTotalSimplePublicObjectForwardPaging response = check baseClient->/crm/v3/objects/feedback_submissions/search.post({
        payload = {
            
        }
    });
}
// @test:Config {}
// isolated function  testPost-/crm/v3/objects/feedback_submissions/batch/read_read() {
// }



